apotek/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'apotek'

urlpatterns = [
    path('', views.list_apotek, name="list"),
    path('form', views.form_apotek, name="form"),
    path('register', views.register_apotek, name="register"),
    path('delete', views.delete_apotek, name="delete"),
]

authentication/urls.py
from django.urls import path
from .views import login, logout

app_name = 'authentication'

urlpatterns = [
    path('login', login, name='login'),
    path('logout', logout, name='logout'),
]

balaipengobatan/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'balaipengobatan'

urlpatterns = [
    path('', views.daftar_balai, name='daftar_balai'),
    path('create', views.tambah_balai, name='tambah_balai'),
    path('update', views.update_balai, name='update_balai'),
    path('delete', views.delete_balai, name="delete_balai")
    # dilanjutkan ...
]

list_produk_dibeli/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'list_produk_dibeli'

urlpatterns = [
    path('', views.list_produk_dibeli, name="list"),
    path('form', views.form_list_produk_dibeli, name="form"),
    path('register', views.register_list_produk_dibeli, name="register"),
    path('delete', views.delete_list_produk_dibeli, name="delete"),
]

obat/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'obat'

urlpatterns = [
    path('', views.list_obat, name="list"),
    path('create', views.tambah_obat, name='tambah_obat'),
    path('update', views.update_obat, name='update_obat'),
    path('delete', views.delete_obat, name="delete_obat")
]

produk_apotek/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'produk_apotek'

urlpatterns = [
    path('', views.list_produk_apotek, name="list"),
    path('form', views.form_produk_apotek, name="form"),
    path('register', views.register_produk_apotek, name="register"),
    path('delete', views.delete_produk_apotek, name="delete"),
]

profil/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'profil'

urlpatterns = [
    path('', views.profil_anda, name="profil"),
]

signup/urls.py
from django.urls import path
from . import views

app_name = 'signup'

urlpatterns = [
    path('konsumen', views.insertKonsumen, name='konsumen'),
    path('kurir', views.insertKurir, name='kurir'),
    path('admin', views.insertAdmin, name='admin'),
    path('cs', views.insertCS, name='cs'),
]

apotek/models.py
from django.db import models

# Nothing here

balaipengobatan/models.py
from django.db import models

# Create your models here.

list_produk_dibeli/models.py
from django.db import models

# Create your models here.

apotek/forms.py
from django import forms

class ApotekForm(forms.Form):

    nama_apotek = forms.CharField(label="Nama Apotek", required=True, max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Kimia Farmasi'}))
    alamat_apotek = forms.CharField(label="Alamat Apotek", required=True,
        widget=forms.Textarea(attrs={'placeholder': 'Jl. Sucipto No. 9'}))
    telepon_apotek = forms.CharField(label="No Telp Apotek", max_length=20, 
        widget=forms.TextInput(attrs={'placeholder': '+62 876 23232323'}))
    nama_penyelenggara = forms.CharField(label="Nama Penyelenggara", required=True, max_length=50, 
        widget=forms.TextInput(attrs={'placeholder': 'Ahmad Darwin'}))
    no_sia = forms.CharField(label="No SIA Penyelenggara", required=True, max_length=20, 
        widget=forms.TextInput(attrs={'placeholder': '838787236'}))
    email = forms.CharField(label="Email Penyelenggara", required=True, max_length=50, 
        widget=forms.EmailInput(attrs={'placeholder': 'ahmad@email.com'}))

transaksi_pembelian/forms.py
from django import forms
from django.db import connection

konsumen_choices = []
with connection.cursor() as cursor:
    cursor.execute('SELECT id_konsumen FROM transaksi_pembelian')
    row = cursor.fetchall()
for id_produk in row:
    konsumen_choices.append((id_produk[0], id_produk[0]))

class TransaksiPembelianForm(forms.Form):
 
    id_konsumen = forms.ChoiceField(label="ID Konsumen", widget=forms.Select(), 
        choices=konsumen_choices, initial=konsumen_choices[0][0])

apotek/views.py
from django.shortcuts import render, redirect
from django.db import connection
from .forms import ApotekForm

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def list_apotek(request):
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM apotek')
        list_apotek = dictfetchall(cursor)
    context = { 'list_apotek': list_apotek }
    return render(request, 'apotek.html', context)

def form_apotek(request):
    context = {}
    if request.method == 'POST':
        context['form'] = ApotekForm(request.POST)
        context['id_apotek'] = request.POST['id_apotek']
        context['action'] = 'Update'
    else:
        context['form'] = ApotekForm()
        context['action'] = 'Create'
    return render(request, 'form-apotek.html', context)

def register_apotek(request):
    if request.method == 'POST':
        nama_apotek = request.POST['nama_apotek']
        alamat_apotek = request.POST['alamat_apotek']
        telepon_apotek = request.POST['telepon_apotek']
        nama_penyelenggara = request.POST['nama_penyelenggara']
        no_sia = request.POST['no_sia']
        email = request.POST['email']
        if request.POST['action'] == 'Update':
            id_apotek = request.POST['id_apotek']
            with connection.cursor() as cursor:
                cursor.execute('UPDATE apotek SET ' \
                    + 'nama_apotek = %s, alamat_apotek = %s, ' \
                    + 'telepon_apotek = %s, no_sia = %s, email = %s, ' \
                    + 'nama_penyelenggara = %s ' \
                    + 'WHERE id_apotek = %s', \
                    [nama_apotek, alamat_apotek, telepon_apotek, no_sia, email, 
                    nama_penyelenggara, id_apotek])
        elif request.POST['action'] == 'Create':
            with connection.cursor() as cursor:
                cursor.execute('SELECT id_apotek FROM apotek ORDER BY id_apotek DESC LIMIT 1')
                last_id = cursor.fetchone()[0]
                order = int(last_id[5:]) + 1
                id_apotek = 'APTK-%0.4d' % order
                cursor.execute('INSERT INTO apotek VALUES (%s, %s, %s, %s, %s, %s, %s)', \
                    [id_apotek, email, no_sia, nama_penyelenggara, nama_apotek, alamat_apotek, telepon_apotek])
        return redirect('apotek:list')
    else:
        return redirect('apotek:form')

def delete_apotek(request):
    if request.method == 'POST':
        id_apotek = request.POST['id_apotek']
        with connection.cursor() as cursor:
            cursor.execute('DELETE FROM apotek WHERE id_apotek = %s', [id_apotek])
        return redirect('apotek:list')
    else:
        return render(request, 'notfound.html')

balaipengobatan/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.utils.datastructures import MultiValueDictKeyError

# Create your views here.

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def daftar_balai(request):
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM balai_pengobatan ORDER BY nama_balai ASC')
        balai_pengobatan = dictfetchall(cursor)
        
        cursor.execute('SELECT * FROM balai_apotek b, apotek a WHERE b.id_apotek = a.id_apotek')
        balai_apotek = dictfetchall(cursor)

    result = {
        'balai_pengobatan': balai_pengobatan,
        'balai_apotek' : balai_apotek
    }
    return render(request, 'balaipengobatan.html', result)

def tambah_balai(request):
    with connection.cursor() as cursor:
        cursor.execute('SELECT id_apotek, nama_apotek FROM apotek ORDER BY nama_apotek ASC')
        list_apotek_asosiasi = dictfetchall(cursor)
        banyak_apotek = len(list_apotek_asosiasi)

        cursor.execute('SELECT id_balai FROM balai_pengobatan ORDER BY id_balai DESC LIMIT 1')
        last_id = cursor.fetchone()[0]

        cursor.execute('SELECT alamat_balai FROM balai_pengobatan')
        list_alamat = dictfetchall(cursor)

        # min ascii A = 65, max ascii Z = 90
        counter = int(last_id[6:]) + 1
        idbalai = ""
        if counter == 1000:
            counter -= 1000
            new = chr(ord(last_id[4]) + 1)
            idbalai = last_id[:4] + str(new) + ('%0.3d' % counter)
            if ord(new) == 91 :
                new = 'A'
                new2 = chr(ord(last_id[3]) + 1)
                idbalai = last_id[:3] + str(new2) + str(new) + ('%0.3d' % counter)
        else:
            idbalai = last_id[:6] + str(counter)
    baru = []
    for i in list_alamat:
        baru.append(i.get("alamat_balai"))

    print(baru)
    temp = idbalai

    if request.method == 'POST':
        id_balai = temp
        alamat = request.POST['alamat']
        nama = request.POST['nama']
        jenis = request.POST['jenis']
        telepon = request.POST['telepon']
        asosiasi_apotek = []
        for i in range(banyak_apotek):
            cb = 'cb' + str(i)
            id_ap = 'id' + str(i)
            temp_cb = request.POST[cb]
            temp_id = request.POST[id_ap]
            if temp_cb == 'on':
                asosiasi_apotek.append(temp_id)

        if alamat not in baru:
            with connection.cursor() as cursor:
                cursor.execute('INSERT INTO balai_pengobatan VALUES (%s, %s, %s, %s, %s)', [id_balai, alamat, nama, jenis, telepon])
                for item in asosiasi_apotek:
                    cursor.execute('INSERT INTO balai_apotek VALUES (%s, %s)', [id_balai, item[:9]])
            return redirect('balaipengobatan:daftar_balai')
        
        is_error = True
        pesan = {
            'list_apotek_asosiasi' : list_apotek_asosiasi,
            'is_error' : is_error
        }
        return render(request, 'tambahbalai.html', pesan)
    else:
        daftar = {
            'list_apotek_asosiasi' : list_apotek_asosiasi,
        }
    return render(request, 'tambahbalai.html', daftar)

def update_balai(request):
    try:
        if request.method == 'GET':
            id_balai = request.GET['id_balai']
        else:
            id_balai = request.POST['id_balai']
    except:
        return render(request, 'updatebalai.html', {'is_failed' : True})

    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM apotek ORDER BY nama_apotek ASC')
        list_update_apotek = dictfetchall(cursor)
        banyak_apotek = len(list_update_apotek)

        cursor.execute('SELECT alamat_balai FROM balai_pengobatan')
        list_alamat = dictfetchall(cursor)

        cursor.execute('SELECT * FROM balai_pengobatan  WHERE id_balai = %s', \
            [id_balai])
        list_update = dictfetchall(cursor)

        cursor.execute('SELECT id_apotek FROM balai_apotek WHERE id_balai = %s', [id_balai])
        temp = dictfetchall(cursor)

        cursor.execute('SELECT id_balai FROM balai_pengobatan')
        temp2 = dictfetchall(cursor)

        list_asosiasi = []
        for i in temp:
            list_asosiasi.append(i.get('id_apotek'))

        list_balai = []
        for j in temp2:
            list_balai.append(j.get('id_balai'))

    baru = []
    for i in list_alamat:
        baru.append(i.get("alamat_balai"))

    if id_balai not in list_balai:
        return render(request, 'updatebalai.html', {'is_failed' : True})

    if request.method == 'POST':
        old_alamat = request.POST['old_alamat']
        alamat = request.POST['alamat']
        nama = request.POST['nama']
        jenis = request.POST['jenis']
        telepon = request.POST['telepon']
        asosiasi_apotek = []
        for i in range(banyak_apotek):
            cb = 'cb' + str(i)
            id_ap = 'id' + str(i)
            temp_cb = request.POST[cb]
            temp_id = request.POST[id_ap]
            if temp_cb == 'on':
                asosiasi_apotek.append(temp_id)
        baru.remove(old_alamat)
        
        if alamat not in baru:
            with connection.cursor() as cursor:
                cursor.execute('UPDATE balai_pengobatan SET ' \
                    + 'alamat_balai = %s, nama_balai = %s, ' \
                    + 'jenis_balai = %s, telepon_balai = %s '\
                    + 'WHERE id_balai = %s', [alamat, nama, jenis, telepon, id_balai])
                cursor.execute('DELETE FROM balai_apotek WHERE id_balai = %s', [id_balai])
                for item in asosiasi_apotek:
                    cursor.execute('INSERT INTO balai_apotek VALUES (%s, %s)', [id_balai, item[:9]])
            return redirect('balaipengobatan:daftar_balai')

        is_error = True
        pesan = {
            'list_update' : list_update,
            'list_update_apotek' : list_update_apotek,
            'list_apotek_asosiasi' : list_asosiasi,
            'is_error' : is_error,
            'idbalai' : id_balai
        }
        return render(request, 'updatebalai.html', pesan)

    daftar_update = {
        'list_update' : list_update,
        'list_update_apotek' : list_update_apotek,
        'list_apotek_asosiasi' : list_asosiasi,
        'idbalai' : id_balai
    }
    return render(request, 'updatebalai.html', daftar_update)

def delete_balai(request):
    try:
        id_balai = request.POST['id_balai']
        with connection.cursor() as cursor:
            cursor.execute('DELETE FROM balai_pengobatan WHERE id_balai = %s', [id_balai])
        return redirect('balaipengobatan:daftar_balai')
    except:
        return render(request, 'notfound.html')

list_produk_dibeli/views.py
from django.shortcuts import render, redirect
from django.db import connection
from .forms import *

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def list_produk_dibeli(request):
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM list_produk_dibeli')
        list_produk_dibeli = dictfetchall(cursor)
    return render(request, 'list-produk-dibeli.html', {'list_produk_dibeli':list_produk_dibeli})

def form_list_produk_dibeli(request):
    context = {}
    
    if request.method == 'POST':
        form = ListProdukDibeliForm(request.POST)
        form.fields['id_apotek'].widget = forms.HiddenInput()
        form.fields['id_produk'].widget = forms.HiddenInput()
        context['form'] = form
        context['id_produk'] = request.POST['id_produk']
        context['id_apotek'] = request.POST['id_apotek']
        context['id_transaksi_pembelian'] = request.POST['id_transaksi_pembelian']
        context['action'] = 'Update'

    else:
        context['form'] = ListProdukDibeliForm()
        context['action'] = 'Create'
    return render(request, 'form-list-produk-dibeli.html', context)

def register_list_produk_dibeli(request):
    if request.method == 'POST':
        context = { 'form': ListProdukDibeliForm(request.POST) }
        id_produk = request.POST['id_produk']
        id_apotek = request.POST['id_apotek']
        id_transaksi_pembelian = request.POST['id_transaksi_pembelian']
        jumlah = request.POST['jumlah']

        # check if primary key exists => error
        with connection.cursor() as cursor:
            cursor.execute('SELECT * FROM list_produk_dibeli WHERE id_apotek = %s AND id_produk = %s AND id_transaksi_pembelian = %s',
            [id_apotek, id_produk, id_transaksi_pembelian])
            row = cursor.fetchone()
        if row:
            if request.POST['action'] == 'Create':
                context['error'] = "Antara ID produk dan ID apotek atau ID Transaksi sudah terambil."
                context['action'] = request.POST['action']
                return render(request, 'form-list-produk-dibeli.html', context)

        if request.POST['action'] == 'Update':
            old_id_transaksi_pembelian = request.POST['old_id_transaksi_pembelian']
            with connection.cursor() as cursor:
                cursor.execute('UPDATE list_produk_dibeli SET ' \
                    + 'id_apotek = %s, id_produk = %s, ' \
                    + 'id_transaksi_pembelian = %s, ' \
                    + 'jumlah = %s ' \
                    + 'WHERE id_apotek = %s AND id_produk = %s AND id_transaksi_pembelian = %s', \
                    [id_apotek, id_produk, id_transaksi_pembelian, jumlah, 
                    id_apotek, id_produk, old_id_transaksi_pembelian])
        elif request.POST['action'] == 'Create':
            with connection.cursor() as cursor:
                cursor.execute('INSERT INTO list_produk_dibeli(id_apotek, id_produk, id_transaksi_pembelian, jumlah) VALUES (%s, %s, %s, %s)', \
                    [id_apotek, id_produk, id_transaksi_pembelian, jumlah])
        return redirect('list_produk_dibeli:list')
    else:
        return redirect('list_produk_dibeli:form')

def delete_list_produk_dibeli(request):
    id_produk = request.POST['id_produk']
    id_apotek = request.POST['id_apotek']
    id_transaksi_pembelian = request.POST['id_transaksi_pembelian']
    with connection.cursor() as cursor:
        cursor.execute('DELETE FROM list_produk_dibeli WHERE id_apotek = %s AND id_produk = %s AND id_transaksi_pembelian = %s', \
            [id_apotek, id_produk, id_transaksi_pembelian])
    return redirect('list_produk_dibeli:list')

templates/apotek.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Daftar Apotek {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% endblock %}

{% block content %}
<div class="layout">
	{% if 'auth' in request.session %}
	<div class="header">
		<h2>Daftar Apotek</h2>
		{% if 'admin' in request.session.role %}
			<a class="btn create" href="{% url 'apotek:form' %}">Create</a>
		{% endif %}
	</div>
	<table class="table">
		<thead class="thead-light">
			<tr>
				<th scope="col">ID Apotek</th>
				<th scope="col">Nama Apotek</th>
				<th scope="col">Alamat Apotek</th>
				<th scope="col">No Telp Apotek</th>
				<th scope="col">Nama Penyelenggara</th>
				<th scope="col">No SIA Penyelenggara</th>
				<th scope="col">Email Penyelenggara</th>
				{% if 'admin' in request.session.role %}
					<th scope="col">Action</th>
				{% endif %}
			</tr>
		</thead>
		<tbody>
			{% for apotek in list_apotek %}
			<tr>
				<td>{{ apotek.id_apotek }}</td>
				<td>{{ apotek.nama_apotek }}</td>
				<td>{{ apotek.alamat_apotek }}</td>
				<td>{{ apotek.telepon_apotek }}</td>
				<td>{{ apotek.nama_penyelenggara }}</td>
				<td>{{ apotek.no_sia }}</td>
				<td>{{ apotek.email }}</td>
				{% if 'admin' in request.session.role %}
					<td>
						<form action="{% url 'apotek:form' %}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="id_apotek" value="{{ apotek.id_apotek }}">
							<input type="hidden" name="nama_apotek" value="{{ apotek.nama_apotek }}">
							<input type="hidden" name="alamat_apotek" value="{{ apotek.alamat_apotek }}">
							<input type="hidden" name="telepon_apotek" value="{{ apotek.telepon_apotek }}">
							<input type="hidden" name="nama_penyelenggara" value="{{ apotek.nama_penyelenggara }}">
							<input type="hidden" name="no_sia" value="{{ apotek.no_sia }}">
							<input type="hidden" name="email" value="{{ apotek.email }}">
							<button type="submit" class="btn update" style="margin-bottom: 0.5rem;">Update</button>
						</form>
						<form action="{% url 'apotek:delete' %}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="id_apotek" value="{{ apotek.id_apotek }}">
							<button type="submit" class="btn delete">Delete</button>
						</form>
					</td>
				{% endif %}
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<div class="center" style="height: 80vh;">
		<h1>Maaf, anda harus <a href="{% url 'authentication:login' %}">login</a> terlebih dahulu.
		</h1>
	</div>
	{% endif %}
</div>    
{% endblock %}

templates/balaipengobatan.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% if 'auth' in request.session %} Daftar Balai Pengobatan
{% else %} Farmakami
{% endif %}
{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
<style type="text/css">
.center {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 80vh;
}  
</style>
{% endblock %}
{% block content %}

<div class="layout">
    {% if 'auth' in request.session %}
    <div class="header">
        <h2> Daftar Balai Pengobatan </h2>
        {% if 'admin' in request.session.role %}
        <div>
            <a class="btn create" href="{% url 'balaipengobatan:tambah_balai' %}" role="button">Create</a>    
        </div>
        {% endif %}
    </div>
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">No.</th>
                <th scope="col">ID Balai</th>
                <th scope="col">Alamat Balai</th>
                <th scope="col">Nama Balai</th>
                <th scope="col">Jenis Balai</th>
                <th scope="col">No. Telepon</th>
                <th scope="col">Apotek yang Berasosiasi</th>
                {% if 'admin' in request.session.role %}
                <th scope="col">Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for balai in balai_pengobatan %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{ balai.id_balai }}</td>
                    <td>{{ balai.alamat_balai }}</td>
                    <td>{{ balai.nama_balai }}</td>
                    <td>{{ balai.jenis_balai }}</td>
                    <td>{{ balai.telepon_balai }}</td>
                    <td>
                        <ul>
                        {% for ap in balai_apotek %}
                        {% if ap.id_balai == balai.id_balai %}
                        <li>{{ ap.id_apotek }} ({{ap.nama_apotek}}) </li>
                        {% endif %}
                        {% endfor %}
                        </ul>
                    </td>
                    {% if 'admin' in request.session.role %}
                    <td>
                        <form action="{% url 'balaipengobatan:update_balai' %}">
                            <input type="hidden" name="id_balai" value="{{ balai.id_balai }}">
                            <button type="submit" class="btn update">Update</button>
                        </form>
                        <form action="{% url 'balaipengobatan:delete_balai' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="id_balai" value="{{ balai.id_balai }}">
                            <button type="submit" class="btn delete">Delete</button>
                        </form>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="center">
        <h1>Maaf, anda harus <a href="{% url 'authentication:login' %}">login</a> terlebih dahulu. </h1>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/form-produk-apotek.html
{% extends 'base.html' %}

{% load static %}
{% block title %} {{ action }} Produk Apotek {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form-apotek.css' %}">
{% endblock %}

{% block content %}
<div class="layout center">
	{% if 'admin' in request.session.role %}
		<h2>Form {{ action }} Produk Apotek</h2>
		<form action="{% url 'produk_apotek:register' %}" method="POST">
			{% csrf_token %}
			<div class="form">
				{{ form }}
			</div>
			<input type="hidden" name="action" value="{{ action }}">
			<input type="hidden" name="old_id_produk" value="{{ id_produk }}">
			<input type="hidden" name="old_id_apotek" value="{{ id_apotek }}">
			<div class="center">
				<button type="submit" class="btn">Submit</button>
				<p class="error">{{ error }}</p>
			</div>
		</form> 
	{% elif 'auth' in request.session %}
		<div class="center" style="height: 80vh;">
			<h1>Maaf, form ini hanya untuk admin.</h1>
			<p>Kembali ke <a href="{% url 'produk_apotek:list' %}">Daftar Produk Apotek</a></p>
		</div>
	{% else %}
		<div class="center" style="height: 80vh;">
			<h1>Maaf, anda harus <a href="{% url 'authentication:login' %}">login</a> terlebih dahulu.
			</h1>
		</div>
	{% endif %}
</div>    
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Farmakami: Login {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="layout center">
	<h2>Login</h2>
	<form action="{% url 'authentication:login' %}" method="POST">
		{% csrf_token %}
		<div class="form">
			{{ form }}
		</div>
		<div class="center">
			<button type="submit" class="btn">Login</button>
			<p class="error">{{ error }}</p>
		</div>
	</form> 
</div>    
{% endblock %}

templates/notfound.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Farmakami {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/errorpage.css' %}">
{% endblock %}

{% block content %}
<div class="center">
    <img src="{% static 'images/notfound.png' %}" alt="Halaman tidak ditemukan" id="background">
</div>    
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Farmakami: Signup {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block content %}
<div class="layout center">
    <h2>Sign Up</h2>
	{% if 'admin' in request.session.signup %}
		<form action="{% url 'signup:admin' %}" method="POST">
            {% csrf_token %}
            <div class="form">
                {{ form }}
            </div>
    {% elif 'cs' in request.session.signup %}
        <form action="{% url 'signup:cs' %}" method="POST">
            {% csrf_token %}
            <div class="form">
                {{ form }}
            </div>
    {% elif 'konsumen' in request.session.signup %}
        <form action="{% url 'signup:konsumen' %}" method="POST">
            {% csrf_token %}
            <div class="form">
                {{ form }}
                <label>Alamat:</label>
                <div class="input-address">
                    <input type="text" name="status1" class="inline-flex third-width" placeholder="aktif">
                    <input type="text" name="alamat1" class="inline-flex" placeholder="Jl. Basdat C">
                </div>
            </div>
            <div id="add_image">
                <img src="{% static 'images/add_alamat.png' %}" alt="add" id="addimg">....
            </div>
    {% elif 'kurir' in request.session.signup %}
		<form action="{% url 'signup:kurir' %}" method="POST">
            {% csrf_token %}
            <div class="form">
                {{ form }}
            </div>
    {% endif %}
            <div class="center">
                <button type="submit" class="btn">Register</button>
                <p class="error">{{ error }}</p>
            </div>
        </form> 
</div>

<script type="text/javascript" src="{% static 'js/signup.js' %}"></script>
{% endblock %}